conditioner:
  params:
    main_image_encoder:
      kwargs:
        config:
          attention_probs_dropout_prob: 0.0
          drop_path_rate: 0.0
          hidden_act: gelu
          hidden_dropout_prob: 0.0
          hidden_size: 1024
          image_size: 518
          initializer_range: 0.02
          layer_norm_eps: 1.0e-06
          layerscale_value: 1.0
          mlp_ratio: 4
          model_type: dinov2
          num_attention_heads: 16
          num_channels: 3
          num_hidden_layers: 24
          patch_size: 14
          qkv_bias: true
          torch_dtype: float32
          use_swiglu_ffn: false
        image_size: 518
        use_cls_token: true
      type: DinoImageEncoder
  target: hy3dshape.models.conditioner.SingleImageEncoder
image_processor:
  params:
    border_ratio: 0.15
    size: 512
  target: hy3dshape.preprocessors.ImageProcessorV2
model:
  params:
    context_dim: 1024
    depth: 21
    hidden_size: 2048
    in_channels: 64
    input_size: 4096
    moe_top_k: 2
    num_experts: 8
    num_heads: 16
    num_moe_layers: 6
    qk_norm: true
    qk_norm_type: rms
    qkv_bias: false
    text_len: 1370
    use_attention_pooling: false
    use_pos_emb: false
    with_decoupled_ca: false
  target: hy3dshape.models.denoisers.hunyuandit_ours.HunYuanDiTPlain
pipeline:
  target: hy3dshape.pipelines.Hunyuan3DDiTFlowMatchingPipeline
scheduler:
  params:
    num_train_timesteps: 1000
  target: hy3dshape.schedulers.FlowMatchEulerDiscreteScheduler
vae:
  params:
    embed_dim: 64
    geo_decoder_downsample_ratio: 1
    geo_decoder_ln_post: true
    geo_decoder_mlp_expand_ratio: 4
    heads: 16
    include_pi: false
    num_decoder_layers: 16
    num_encoder_layers: 8
    num_freqs: 8
    num_latents: 4096
    pc_sharpedge_size: 0
    pc_size: 81920
    point_feats: 4
    qk_norm: true
    qkv_bias: false
    scale_factor: 1.0039506158752403
    width: 1024
  target: hy3dshape.models.autoencoders.ShapeVAE
